title: CCA
log_dir: log
seeds: [233, 42, 1135]
data:
  path: twlvsplit
  num_workers: 2
model: 
  name: ConditionalAutoencoderCC
  in_channels: 79
  # Hao Model
  # out_channels: 6
  # hidden_channels: [32, 6]
  # CACC
  out_channels: 3
  hidden_channels: [32, 16, 8, 6]
  dropout: 0.1
  device: "cuda:0"
  # device: cpu
  loss_fn: MSELoss
optimizer:
  name: Adam
  lr: 0.005
  scheduler: exp
train:
  batch_size: 16
  num_epochs: 1000
  drop_last: False
evaluator: r2_total